// File shared by kernel/shell about error codes


#ifndef PENNOS_ERROR_CODES_H
#define PENNOS_ERROR_CODES_H

#define E_NO_INIT_PROCESS -1
#define E_INIT_ALREADY_EXISTS -2
#define E_FAILED_TO_ALLOCATE -3
#define E_BAD_ARGV -4
#define E_STR_FORMAT_FAILED -5
#define E_STR_TOO_LONG_FOR_FPRINTF_BUF -6
#define E_INVALID_PCB -7
#define E_INVALID_SCHEDULER_STATE -8
#define E_NO_SUCH_PROCESS -9
#define E_INVALID_ARGUMENT -10
#define E_TRIED_TO_KILL_INIT -11
#define E_TCSET_NO_TERMINAL_CONTROL -12
#define E_CONTINUE_NON_STOPPED_PROCESS -13
#define E_STOP_STOPPED_PROCESS -14
#define E_STOP_NON_ACTIVE_QUEUE_PROCESS -15
#define E_PID_NOT_FOUND -16
#define E_NO_CURRENT_PROCESS -17

// these are bad errors -- almost panics
#define E_RUNNING_PROCESS_NOT_IN_READY_QUEUE -18

// fs kernel errors
#define EK_OPEN_INVALID_FILENAME -19
#define EK_OPEN_FIND_FILE_IN_ROOT_DIR_FAILED -20
#define EK_OPEN_GLOBAL_FD_TABLE_FULL -21
#define EK_OPEN_FILE_DOES_NOT_EXIST -22
#define EK_OPEN_MALLOC_FAILED -23
#define EK_OPEN_TIME_FAILED -24
#define EK_OPEN_ALREADY_WRITE_LOCKED -25
#define EK_OPEN_WRITE_NEW_ROOT_DIR_ENTRY_FAILED -26
#define EK_OPEN_NO_EMPTY_BLOCKS -27
#define EK_OPEN_WRONG_PERMISSIONS -28
#define EK_OPEN_WRITE_ROOT_DIR_ENTRY_FAILED -29

#define EK_CLOSE_FD_OUT_OF_RANGE -30
#define EK_CLOSE_SPECIAL_FD -31
#define EK_CLOSE_WRITE_ROOT_DIR_ENTRY_FAILED -32


#define EK_READ_FD_OUT_OF_RANGE -33
#define EK_READ_FD_NOT_IN_TABLE -34
// this is an unexpected error (almost a panic) because
// this should never happen if lseek is implemented correctly
#define EK_READ_COULD_NOT_JUMP_TO_BLOCK_FOR_OFFSET -35
#define EK_READ_WRONG_PERMISSIONS -36
#define EK_READ_READ_FAILED -37

#define EK_LSEEK_BAD_WHENCE -38
#define EK_LSEEK_NEGATIVE_OFFSET -39
#define EK_LSEEK_OFFSET_OVERFLOW -40
#define EK_LSEEK_FD_OUT_OF_RANGE -41
#define EK_LSEEK_FD_NOT_IN_TABLE -42
#define EK_LSEEK_WRONG_PERMISSIONS -43
#define EK_LSEEK_SPECIAL_FD -44

#define EK_WRITE_WRONG_PERMISSIONS -45
#define EK_WRITE_FD_NOT_IN_TABLE -46
#define EK_WRITE_FD_OUT_OF_RANGE -47
#define EK_WRITE_GET_BLOCK_FAILED -48
#define EK_WRITE_NEXT_BLOCK_NUM_FAILED -49
#define EK_WRITE_WRITE_BLOCK_FAILED -50
#define EK_WRITE_WRITE_ROOT_DIR_ENTRY_FAILED -51
#define EK_WRITE_NO_EMPTY_BLOCKS -52
#define EK_WRITE_TIME_FAILED -53
#define EK_WRITE_WRITE_FAILED -54

#define EK_UNLINK_FILE_NOT_FOUND -55
#define EK_UNLINK_FIND_FILE_IN_ROOT_DIR_FAILED -56
#define EK_UNLINK_WRITE_ROOT_DIR_ENTRY_FAILED -57
#define EK_UNLINK_INVALID_FILENAME -58

#define EK_LS_WRITE_FAILED -59
#define EK_LS_FIND_FILE_IN_ROOT_DIR_FAILED -60
#define EK_LS_NOT_IMPLEMENTED -61
#define EK_LS_MALLOC_FAILED -62
#define EK_LS_GET_BLOCK_FAILED -63
#define EK_LS_NEXT_BLOCK_NUM_FAILED -64

#define EK_CHMOD_FILE_NOT_FOUND -65
#define EK_CHMOD_WRITE_ROOT_DIR_ENTRY_FAILED -66
#define EK_CHMOD_WRONG_PERMISSIONS -67
#define EK_CHMOD_INVALID_FILENAME -68
#define EK_CHMOD_INVALID_MODE -69

#define EK_MV_FILE_NOT_FOUND -70
#define EK_MV_WRONG_PERMISSIONS -71
#define EK_MV_UNLINK_FAILED -72
#define EK_MV_INVALID_FILENAME -73
#define EK_MV_OPEN_FAILED -74
#define EK_MV_WRITE_ROOT_DIR_ENTRY_FAILED -75
#define EK_MV_CLOSE_FAILED -76

#define EK_SETMODE_FD_OUT_OF_RANGE -77
#define EK_SETMODE_BAD_MODE -78
#define EK_SETMODE_FD_NOT_IN_USE -79

#define EK_GETMODE_FD_OUT_OF_RANGE -80
#define EK_GETMODE_FD_NOT_IN_USE -81

// fs syscall errors
#define E_UNKNOWN_FD -103
#define E_PROCESS_FILE_TABLE_FULL -100
#define E_READ_UNKNOWN_FD -101
#define E_STRING_FORMAT_FAILED -104
#define E_STRING_TOO_LONG_FOR_PRINTF_BUF -105


#endif // PENNOS_ERROR_CODES_H
